<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JPMORGAN_LOANS_BusinessEntities\JPMORGAN_LOANS_BusinessEntities.csproj" />
    <ProjectReference Include="..\JPMORGAN_LOANS_RepositoryLayer\JPMORGAN_LOANS_RepositoryLayer.csproj" />
  </ItemGroup>

</Project>
